version: '3.8'

services:
  gateway:
    build:
      context: ../devoops-gateway-service
      dockerfile: Dockerfile
    container_name: devoops-gateway-service
    ports:
      - "8080:8080"
    env_file:
      - "../devoops-gateway-service/environment/.local.env"
    networks:
      - devoops-network
    restart: unless-stopped
    depends_on:
      - user-service
      - accommodation-service
      - notification-service
      - rating-service
      - reservation-service
      - search-service

  user-service:
    build:
      context: ../devoops-user-service
      dockerfile: Dockerfile
    container_name: devoops-user-service
    ports:
      - "8081:8080"
    env_file:
      - "../devoops-user-service/environment/.local.env"
    networks:
      - devoops-network
    restart: unless-stopped

  accommodation-service:
    build:
      context: ../devoops-accommodation-service
      dockerfile: Dockerfile
    container_name: devoops-accommodation-service
    ports:
      - "8082:8080"
    env_file:
      - "../devoops-accommodation-service/environment/.local.env"
    networks:
      - devoops-network
    restart: unless-stopped

  notification-service:
    build:
      context: ../devoops-notification-service
      dockerfile: Dockerfile
    container_name: devoops-notification-service
    ports:
      - "8083:8080"
    env_file:
      - "../devoops-notification-service/environment/.local.env"
    networks:
      - devoops-network
    restart: unless-stopped

  rating-service:
    build:
      context: ../devoops-rating-service
      dockerfile: Dockerfile
    container_name: devoops-rating-service
    ports:
      - "8084:8080"
    env_file:
      - "../devoops-rating-service/environment/.local.env"
    networks:
      - devoops-network
    restart: unless-stopped

  reservation-service:
    build:
      context: ../devoops-reservation-service
      dockerfile: Dockerfile
    container_name: devoops-reservation-service
    ports:
      - "8085:8080"
    env_file:
      - "../devoops-reservation-service/environment/.local.env"
    networks:
      - devoops-network
    restart: unless-stopped

  search-service:
    build:
      context: ../devoops-search-service
      dockerfile: Dockerfile
    container_name: devoops-search-service
    ports:
      - "8086:8080"
    env_file:
      - "../devoops-search-service/environment/.local.env"
    networks:
      - devoops-network
    restart: unless-stopped

networks:
  devoops-network:
    driver: bridge